name: General Report - Histogram of Issues (all)

on:
  schedule:
    - cron: '0 0 * * SUN'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install PyGithub matplotlib

      - name: Run histogram script
        run: python scripts/histogram.py
        env:
          GIT_PAT: ${{ secrets.GH_PAT }}

      - name: Commit and push histogram to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add artifacts/histogram.png
          git commit -m "Auto: Update histogram report" || echo "No changes"
          git pull --rebase origin main
          git push origin main





